### ISSUE TITLE
How to link them together?

### ISSUE THREAD

**Issue by iphyer** [t-/amber-dyes#2]
Hi, suppose I have a PDB of protein and want to use the dye from this directory, so How can I realize this?
I mean I use VMD or PyMoL can achieve this? 
If this can, could you be kind to give me some tutorial?
Thank you!

**Comment by t-** [comment]
If you need to do the labeling once or twice, use PyMol. If you need to do it many times over, the amber-tools will allow you to script the mutation process. However, label placement without clashes will not be possible in all cases and some fine tuning is still required.

In PyMol you can simply load the protein and the FRET label pdb and pull the label in place while leaving the protein PDB unchanged. Then merge the two files and minimize the structure using Gromacs with a steepest decent (steep) minimization (not cg!). This works just fine in most cases. However, make sure that pdb2gmx correctly connects the amino acids to the labels and that the chain does not get broken. You will see this in the pdb2gmx console output. Otherwise you can check if the backbone peptide bonds were written to the topology file correctly.

If your aim is to simulate with a 4 fs time step, please make sure to equilibrate your system beforehand at 1 fs and use larger values for lincs iter / lincs order to prevent crashes.

**Comment by iphyer** [comment]
@t- Thank you! I have solved this problem. Thank you very much!
